from Proceso import Proceso
from FCFS import FCFS
from RR import RR
from SPN import SPN
from SRR import SRR
import random
import time
def main():
    print("Prueba default")
    FCFS_procesoA=Proceso(0,3,"A")
    FCFS_procesoB=Proceso(1,5,"B")
    FCFS_procesoC=Proceso(3,2,"C")
    FCFS_procesoD=Proceso(9,5,"D")
    FCFS_procesoE=Proceso(12,5,"E")
    print("ALGORITMO FCFS")
    AlgoritmoCola=FCFS(FCFS_procesoA, FCFS_procesoB,FCFS_procesoC,FCFS_procesoD,FCFS_procesoE)
    AlgoritmoCola.run()
    RR_procesoA=Proceso(0,3,"A")
    RR_procesoB=Proceso(1,5,"B")
    RR_procesoC=Proceso(3,2,"C")
    RR_procesoD=Proceso(9,5,"D")
    RR_procesoE=Proceso(12,5,"E")
    print("ALGORITMO RR")
    AlgorDos=RR(RR_procesoA, RR_procesoB,RR_procesoC,RR_procesoD,RR_procesoE,1)
    AlgorDos.runRR()
    AlgorDos.listDiaf()
    SPN_procesoA=Proceso(0,3,"A")
    SPN_procesoB=Proceso(1,5,"B")
    SPN_procesoC=Proceso(3,2,"C")
    SPN_procesoD=Proceso(9,5,"D")
    SPN_procesoE=Proceso(12,5,"E")
    print("ALGORITMO SPN")
    Algortres=SPN(SPN_procesoA,SPN_procesoB,SPN_procesoC,SPN_procesoD,SPN_procesoE)
    Algortres.run()
    Algortres.listDiaf()
    # SRR_procesoA=Proceso(0,3,"A")
    # SRR_procesoB=Proceso(1,5,"B")
    # SRR_procesoC=Proceso(3,2,"C")
    # SRR_procesoD=Proceso(9,5,"D")
    # SRR_procesoE=Proceso(12,5,"E")
    # print("ALGORITMO SRR")
    # Algocuatro=SRR(SRR_procesoA,SRR_procesoB,SRR_procesoC,SRR_procesoD,SRR_procesoE,)
    # Algocuatro.run()
    # Algocuatro.listDiaf()
    time.sleep(3)
    repetir=True
    n=0
    while(repetir):
        n+=1
        print("Ronda "+str(n))
        tA=random.randint(1,8)
        cA=random.randint(0,tA-1)
        tB=random.randint(1,8)
        cB=random.randint(0,tB-1)
        tC=random.randint(1,8)
        cC=random.randint(0,tC-1)
        tD=random.randint(1,8)
        cD=random.randint(0,tD-1)
        tE=random.randint(1,8)
        cE=random.randint(0,tE-1)

        FCFS_procesoA=Proceso(cA,tA,"A")
        FCFS_procesoB=Proceso(cB,tB,"B")
        FCFS_procesoC=Proceso(cC,tC,"C")
        FCFS_procesoD=Proceso(cD,tD,"D")
        FCFS_procesoE=Proceso(cE,tE,"E")
        print("ALGORITMO FCFS")
        AlgoritmoCola=FCFS(FCFS_procesoA, FCFS_procesoB,FCFS_procesoC,FCFS_procesoD,FCFS_procesoE)
        AlgoritmoCola.run()
        RR_procesoA=Proceso(cA,tA,"A")
        RR_procesoB=Proceso(cB,tB,"B")
        RR_procesoC=Proceso(cC,tC,"C")
        RR_procesoD=Proceso(cD,tD,"D")
        RR_procesoE=Proceso(cE,tE,"E")
        print("ALGORITMO RR")
        AlgorDos=RR(RR_procesoA, RR_procesoB,RR_procesoC,RR_procesoD,RR_procesoE,1)
        AlgorDos.runRR()
        AlgorDos.listDiaf()
        SPN_procesoA=Proceso(cA,tA,"A")
        SPN_procesoB=Proceso(cB,tB,"B")
        SPN_procesoC=Proceso(cC,tC,"C")
        SPN_procesoD=Proceso(cD,tD,"D")
        SPN_procesoE=Proceso(cE,tE,"E")
        print("ALGORITMO SPN")
        Algortres=SPN(SPN_procesoA,SPN_procesoB,SPN_procesoC,SPN_procesoD,SPN_procesoE)
        Algortres.run()
        Algortres.listDiaf()
        # SRR_procesoA=Proceso(cA,tA,"A")
        # SRR_procesoB=Proceso(cA,tA,"A")
        # SRR_procesoC=Proceso(cA,tA,"A")
        # SRR_procesoD=Proceso(cA,tA,"A")
        # SRR_procesoE=Proceso(cA,tA,"A")
        # print("ALGORITMO SRR")
        # Algocuatro=SRR(SRR_procesoA,SRR_procesoB,SRR_procesoC,SRR_procesoD,SRR_procesoE,)
        # Algocuatro.run()
        # Algocuatro.listDiaf()

        print("Nos echamos otro round? 7u7")
        print("1.- Si 0.- No")
        des=int(input("--"))
        if(des==0):
            repetir=False
main()
